### ISSUE TITLE
Uso de system

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-proyecto-buque-insignia#16]
Debéis evitar el uso de system porque hace llamadas a comandos del sistema operativo y, por tanto, no es portable: lo que funciona en windows no funciona en linux o mac, y viceversa:

https://github.com/aigora/twIE_2021-proyecto-buque-insignia/blob/670b2102df50d3379297ae726f91bfaab0306fff/menu_principal.c#L24

Una solución sencilla es emplear los ANSI escape codes. Hablé de ellos en [una respuesta en el canal de tutorías](https://teams.microsoft.com/l/message/19:98e916bb4a3a46a6ac3150257541425d@thread.tacv2/1615334973963?tenantId=6afea85d-c323-4270-b69d-a4fb3927c254&groupId=3477ddd6-cbb2-4bb5-ad31-ecefaebf2091&parentMessageId=1615327042869&teamName=Inform%C3%A1tica%2056IE%20(2020-21)&channelName=Tutor%C3%ADas&createdTime=1615334973963).

Por ejemplo, para borrar la pantalla probad con:
`printf("\033[2J");`

No olvidéis que necesitaréis [Windows Terminal](https://github.com/microsoft/terminal#installing-and-running-windows-terminal).

**Comment by AdriTeixeHax** [comment]
Me parece lógico. Utilizamos system primeramente para tener un prototipo funcional y después cambiarlo. Sin embargo, llevo teniendo un par de problemas un tiempo:
El primero es que no puedo usar Windows Terminal como ventana de comandos predeterminado.
El segundo, como remedio para el primero, es crear un archivo batch para abrir el programa con Windows Terminal. Si abro el programa desde WT, yendo manualmente a la ruta del archivo y ejecutándolo, no hay ningún problema, pero si lo abro con el .bat no se incluyen los ficheros, a pesar de que están en la misma carpeta que el proyecto (y los he copiado al directorio del ejecutable también). Adjunto imágenes del estado de mi directorio, así como el código del archivo .bat.
La idea es resolver el primer problema, sin tener que andar haciendo archivos batch para poder ejecutar nada. Muchas gracias.

Código del archivo batch:
```
start "" wt "ProyectoBuqueInsignia.exe"
exit
```
![Screenshot (74)](https://user-images.githubusercontent.com/79763356/119149581-f2948580-ba4d-11eb-99a1-3e987e9eb2b1.png)
![Screenshot (73)](https://user-images.githubusercontent.com/79763356/119149585-f32d1c00-ba4d-11eb-9be8-65ca54cdb67b.png)
![Screenshot (72)](https://user-images.githubusercontent.com/79763356/119149587-f3c5b280-ba4d-11eb-99e1-aac3c8b9c4c9.png)

**Comment by AdriTeixeHax** [comment]
He resuelto el problema anterior haciendo que WT se abra automáticamente en el directorio del juego, después sólo hay que abrir el archivo. Detallaré en la wiki los pasos para hacerlo.
