### ISSUE TITLE
Definición de las estructuras

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-proyecto-buque-insignia#5]
Debéis implementar la definición de las principales estructuras (datos tipo `struct`) que se usan en el programa.
Esta implementación puede tener cambios en la versión definitiva.

**Comment by oscarperpinan** [comment]
Uno de los requisitos mínimos en el trabajo es:

> Es obligatorio utilizar vectores de estructuras. 

En vuestro código habéis definido las estructuras pero no estáis usando vectores de estructuras.

**Comment by AdriTeixeHax** [comment]
Tras haber definido y utilizado los vectores de estructuras `usercpu[2]`, `contadorStats[2]` y `flechas[2]`, definidos en el archivo `estructuras.h`, doy por cerrada la issue.

Se añadirán un par de vectores de estructuras más para la versión final, correspondientes a la visualización de puntuaciones.
